name: "RunGoTestAndVetOn17181920"
on: ["push"]

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macOS-latest","centos-latest"]
        go: ["1.17.x", "1.18.x","1.19.x","1.20.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3.4.0
      with:
        fetch-depth: 1

    - uses: actions/setup-go@v4.0.0
      with:
        go-version: ${{ matrix.go }}
    - run: "go test ./..."
    - run: "go vet ./..."
